---
title: "R Notebook"
output: html_notebook
params: 
  data: "/Users/bella/Desktop/Psychologie/Versuchsplanung/RTutorium"
---

```{r}
#loading packages and importing data
pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, 
  ggvis, httr, lubridate, plotly, rio, rmarkdown, shiny, 
  stringr, tidyr, gtools)
library(tidyverse)
library(tidyverse)
library(ggpubr)
library(rstatix)
params$data
HA01rawdata <- read_csv(file.path(params$data, "1-HA-download.csv"))

#tidying data & defining variables
HA01data <- HA01rawdata |>
  mutate_at(vars(c("gender", "department")), factor)
HA01data$gender <- factor(HA01data$gender,
                          levels = c(1, 2, 3),
                          labels = c("w", "m", "d"))
HA01data$department <- factor(HA01data$department,
                              levels = c("A", "B", "C", "D", "E", "F"),
                              labels = c("Psy", "Phys", "Chem", "Bio", "Math", "Pharm"))
#values of id=150
HA01data[150,]

#counting departments
HA01data |>
  count(department)

#plotting department count 
ggplot(HA01data) +
  geom_bar(aes(department, fill = gender))
```


```{r}
#work in progress
#y <- HA01data|>
 # select(-(id:department)) |>
  #lapply(function(x) ifelse(x %% 2 == 0, abs(x - 6), x))

#sub150 <- as.data.frame(lapply(HA01data[150, 5:64], function(x) ifelse(x %% 2 == 0, (x - 6), x))) |>
 # transmute(N = mean(N1:N12),
  #          E = mean(E1:E12),
   #         O = mean(O1:O12),
    #        G = mean(G1:G12),
     #       V = mean(V1:V12))
```


```{r}
#function to recode reverse items: absolute number of (x-6)
recode_items <- function(reverse_items) {
  items <- abs(reverse_items - 6)
  return(items)
}

#testing function
test_function <- recode_items(HA01data[150, 6])

#all following for id 150
#recoding reverse-coded items with custom function, then summarising each trait items
data_recoded <- HA01data |>
    filter(id == 150) |>
    select(matches("(2|4|6|8|0)")) |>
    recode_items()

#summarising each trait items that were not reverse coded
data_rest <- HA01data |>
    filter(id == 150) |>
    select(matches("(1|3|5|7|9)")) |>
    select(-matches("(10|12)"))


#create data frame of all items, then summarising to get total mean for each trait
(data_end <- as.data.frame(c(data_recoded, data_rest)))
Mean <- c(data_end$N <- rowMeans(data_end[,grepl("N",colnames(data_end))]),
                 data_end$E <- rowMeans(data_end[,grepl("E", colnames(data_end))]),
                 data_end$O <- rowMeans(data_end[,grepl("O", colnames(data_end))]),
                 data_end$G <- rowMeans(data_end[,grepl("G", colnames(data_end))]),
                 data_end$V <- rowMeans(data_end[,grepl("V", colnames(data_end))]))
Traits <- c("N", "E", "O", "G", "V")
(results <- tibble(Traits, Mean))

ggplot(results, aes(Traits, Mean)) +
  geom_point()
```

```{r}
#sub150 <- HA01data |>
 # filter(id == 150) |>
  #if_else(contains("2","4","6","8","0"), abs(- 6))
  
  #recode_factor(function(.x) abs(.x - 6))
  
#group_modify(~ function(.x) abs(.x - 6))

 # as.data.frame(lapply(function(x) abs(x - 6))) 

 # transmute(id = id,
  #          age = age,
   #         gender = gender,
    #        department = department,
     #       N = mean(N1:N12),
      #      E = mean(E1:E12),
       #     O = mean(O1:O12),
        #    G = mean(G1:G12),
         #   V = mean(V1:V12))

#  as.data.frame(lapply, function(x) abs(x - 6), x) |>
 # transmute(id = id,
  #          age = age,
   #         gender = gender,
    #        department = department,
     #       N = mean(N1:N12),
      #      E = mean(E1:E12),
       #     O = mean(O1:O12),
        #    G = mean(G1:G12),
         #   V = mean(V1:V12))

#sub150 <- HA01data |>
 # filter(id == 150) |>
  #lapply(ifelse(x %% 2 == 0, abs(x - 6), x)) |>
  #transmute(id = id,
   #         age = age,
    #        gender = gender,
     #       department = department,
      #      N = mean(N1:N12),
       #     E = mean(E1:E12),
        #    O = mean(O1:O12),
         #   G = mean(G1:G12),
          #  V = mean(V1:V12))


```


```{r}
#df for stackoverflow
df1 <- tibble(id = 1:5, N1 = c(4,3,2,5,4), N2 = c(1,1,3,2,5), N3 = c(5,5,2,4,3), N4 = c(4,2,2,2,1), N5 = c(1,1,4,2,3), N6 = c(5,2,4,3,1),
                 E1 = c(1,2,3,1,1), E2 = c(5,2,3,1,1), E3 = c(2,2,1,3,1), E4 = c(1,1,1,3,2), E5 = c(2,3,1,4,4), E6 = c(3,2,3,3,1))

recode_items <- function(reverse_items) {
  items <- abs(reverse_items - 6)
  return(items)
}

#recoded_df1 <- df1 |>
 # filter(id = 3)
  #group_by(across(ends_with(c("2","4","6")))) |>
  #group_modify(~ recode_items(.x)) |>
  #ungroup() |>
  #transmute(id = id, 
   #         N = mean(N1:N6),
    #        E = mean(E1:E6))

#solution
#convert from tibble
df2 <- as.data.frame(df1)

#apply function to all even columns
df2[,-1][,c(FALSE, TRUE)] <- abs(df2[,-1][,c(FALSE, TRUE)]-6)

#calculate row means per group
df2$N <- rowMeans(df2[,grepl("N", colnames(df2))])
df2$E <- rowMeans(df2[,grepl("E", colnames(df2))])
```

